# kubectl apply -f day15-task-nodeffinity.yaml
# kubectl get pod
# kubectl describe pod nginx
# kubectl label node kind-new-cluster-with-ports-worker disktype=ssd
# kubectl get pod
# kubectl label node kind-new-cluster-with-ports-worker disktype-

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
        