apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx-new
spec:
  containers:
  - name: nginx-new
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - hdd
