# kubectl apply -f .\day-8-deploy.yaml
# kubectl get all
# kubectl get deploy --show-labels
# kubectl get pods --show-labels
# kubectl describe deploy nginx
# kubectl rollout history deploy nginx
# kubectl annotate --overwrite deploy/nginx kubernetes.io/change-cause="Pick up patch version"
# kubectl scale deploy/nginx --replicas=5
# kubectl rollout undo deploy nginx --to-revision=1
# kubectl describe deploy nginx


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tier: backend
  name: nginx
spec:
  template:
     metadata:
       labels:
         app: v1
     spec:
       containers:
         - name: nginx
           image: nginx:1.23.4
  replicas: 5
  selector:
    matchLabels:
      app: v1
       
