# kubectl apply -f day18-task2.yaml
# kubectl get pod
# kubectl describe pod agnhost-pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: agnhost-pod
  name: agnhost-pod
spec:
  containers:
  - name: agnhost-pod
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    ports:
    - containerPort: 8080
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10