# kubectl get pods

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-apache
  name: php-apache
spec:
   template:
     metadata:
       labels:
         app: php-apache
     spec:
       containers:
       - name: php-apache
         image: registry.k8s.io/hpa-example
         ports:
         - containerPort: 80
         resources:
           requests:
             cpu: "200m"
           limits:
             cpu: "500m"
   selector:
     matchLabels:
       app: php-apache