# kubectl apply -f myservice.yaml
# kubectl get all

apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: myservice
  name: myservice
spec:
  ports:
  - port: 80


---

apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: myservice1
  name: myservice1
spec:
  ports:
  - port: 80