# openssl genrsa -out krishna.key 2048
# openssl req -new -key krishna.key -out krishna.csr -subj "//CN=krishna"
# kubectl config get-contexts
# kubectl auth whoami
# kubectl auth can-i get pods
# kubectl auth can-i get pods --as krishna
# kubectl apply -f krishna_csr.yaml
# kubectl get csr
# kubectl certificate approve krishna
# kubectl get csr krishna -o yaml > krishna_crt.yaml

apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: krishna
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWekNDQVQ4Q0FRQXdFakVRTUE0R0ExVUVBd3dIYTNKcGMyaHVZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUINCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU4vMmNvSG5sZ2RkakJIRTd5YituendMWlFqcGdmdHQybWx6SnU3Z3VHRnENCkFqeTQremo1a1I2M3lRZWl6SE5LTVhjLy9xQkFLK1FmSlZ6dDhJbnFXbVBvUzhPY2pKNE5kZVUzcUNVd3Q3VisNCkZ0VHFmVlF1SzFsNFB2a1hOY3cvbEJabjJpK2VEZW9ERkdJelQ4NEFzbmtMbHkwUkVRS3cvT09mejJabi9yQ2MNCmFtbVB6RTZJUzJNWDYyUkJDWUFVQlgwcFRKcVFSR1hITHYxeStQdG1ZZkd5QkdHNE1kUDh3bCtWYkY3aGc0b0QNClc1bHZYSUpYcWRPcU5WNDU3SFJwWGFLUktTdFplOWdzNXVnVFBPdWkrc29DK2tlWVhoSEpZWnBDZ3p1TG4rbUkNClNBMVZPbS9zTW1KckFlMHlJT2tzRUQwbWtqQStra3poOWNrK2UvR1RoZk1DQXdFQUFhQUFNQTBHQ1NxR1NJYjMNCkRRRUJDd1VBQTRJQkFRQzJaSnBnQTZSYU1UZWxxY2sxYjNMbSs1K3FDT2NzTGRTeGRBc0thRnVGSlVGNUNjelkNCnBEQ2hTUVVMUzR4QU1BWnFCVjh1aHJuTFdNelV5VE5kK21RNDdUMlBkU1YzamhBNStHK1pJb3k1S3NRdlZwWFANCjQrb3FwTE1XUXo4blE3bEpoWGNzeG53VzlGN1JBUWdsZmZoV1pFV3VKY2NLVmdOTmlVTlFoWXR2bEN4V1Q1WlINCkhVVEtZdjBkMkdBZC9yNDYxeFpqM05VNnRTWUU5ZlpqVUFhM3lwUFJBTzIwU3ZHemdFdEwxN2VLNk82OTFjakQNCllMZUdUYkNsS1lDVW1PZ0xXRDV6cnVYeXdNSHI1OWVqZW05MjFxNVVEdXg2V3V4K1A1SXVXOEhiMmE3U3pSclgNCnRYQUQxb2RRNURHazBmQUY1RDhyOHd4ZHBRWXQxZmlTTmsvZQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000
  usages:
    - client auth