# openssl genrsa -out learner.key 2025
# openssl req -new -key learner.key -out learner.csr -subj "//CN=learner"
# kubectl apply -f csr.yaml
# kubectl get csr
# kubectl describe csr learner
# kubectl certificate approve learner
# kubectl describe csr learner
# kubectl get csr learner -o yaml > certificate_learner.yaml
# echo "cert" | base64 -d
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: learner
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNVRENDQVRzQ0FRQXdFakVRTUE0R0ExVUVBd3dIYkdWaGNtNWxjakNDQVI0d0RRWUpLb1pJaHZjTkFRRUINCkJRQURnZ0VMQURDQ0FRWUNnZjRCaE9uUzJCQ0pMSjVNd2xFS2dlMFhuS3dKZ1dxZzI3SHhPOG5GOVVvR2VxUVYNClhTMnpJY1BmL3VxcmtVR3FVN0lXcWgrZ1VkanZaY2l3cjg2S1RpTURKZkV6Uk01QVQydUZqU3NBK3lGa3NmWWcNCld1OEpTaXNLWVV2QnZQb2dIbjc4aGw2RjNqZUxhT2NsTjFNMmxkbWJGZmZsOGF5YVl5cmxDbEROMzlaazJobVENCkdUUjc1NVM1NXBQMFRtWXM5bFcxRTFIbENvS040UWhuU0hqMzhCdEU2cStiQXlKaEhqZWpWNU92QnZOekRMTVUNCjVsanJ2Zmt2YUpGMUFMdlNrUEtFNjlrVXNGaDV5ZnUzak5ReGQwd2hTYjY0MFQvWmN5WVFoemExVHhRN2txcW4NCmlvakovTWhwc3dtUDYwemE4V1pWLzFzaC93QXFHTExMZHhzd3BRSURBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUwNCkJRQURnZjhBQUdWVzA1VE5IMU1GOFF6TVFQS3Y3Ym1LSzlnVEk0WTNLU21HUFo5b2ZZMjdUV2tmK1BjYTkrOVANCkxqWVFtOEx5YURKQXU3WGZZS1MyUkxrRHJFOHZrWSt3V2hGaDJTT2hxMnA0dUFKWkkyMzA0UDk0N1dheU94WEYNCjB3d2t1Z3YxL21CaEp6aWpyRHNOVWpNV1NGeGMxbDFTdDFMQXlKd0JSUitmcFNBMXUwblJLYTJzRTNEOXRCOVYNCllXRlh1dmlSYVVtTDFXRkd2aHpidkFpbHhCNU9CNlVWc0p2enZVUmtGOVFUREl2OUM5dHVFSkhWc256bWlEVjcNCkNRbHQ0c3EyZU9kVUZqNHovam1IUVVuMStlWVlGM1RnaWRZbkNqdHViUHlmaVEvUlVVK1NLcHVnbWoxckZxK20NClZWZWx0ZVJqUElQeEpwd25oUTExZnd4SUpuOD0NCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQ0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
    - client auth