# kubectl apply -f .\day-9-task.yaml 
# kubectl get all
# kubectl scale deployment.apps/myapp --replicas=2
# kubectl run busybox-test --rm -it --image=busybox --restart=Never -- sh
# curl http://myapp
# curl http://127.0.0.1
# change service type to nodeport and kubectl apply -f .\day-9-task.yaml
# curl http://127.0.0.1:30001

apiVersion: v1
kind: Service
metadata: 
  name: myapp
  labels:
    app: myapp
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80
  selector:
    app: myapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:1.23.4-alpine
  replicas: 1
  selector:
    matchLabels:
      app: myapp


