# kubectl apply -f nodeport.yaml
# kubectl get svc
# kubectl get pods -o wide

apiVersion: v1
kind: Service
metadata:
   name: nodeport-svc
   labels:
     env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    env: demo
